dist: trusty
sudo: required

addons:
  packages:
    - unzip
    - google-chrome-stable
  firefox: latest

language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository

before_install:
    # Install Chrome driver
    - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - sudo chmod u+x chromedriver
    - sudo mv chromedriver /usr/local/bin/

    # For selenium in headless linux system
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

script:
  - mvn test jacoco:report coveralls:report -Pfirefox -DCI
  - mvn test -Pchrome -DCI