language: java

script: mvn clean install --quiet -B

install: /bin/true

jdk:
  - openjdk7
  - oraclejdk7

branches:
  only:
    - master

notifications:
  email:
    - d.avenante@gmail.com
    - mathieu.carbou@gmail.com
