sudo: required
dist: trusty

addons:
  firefox: latest

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

language: java

jdk:
  - oraclejdk8

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  mvn test -DBrowser=Firefox
  mvn test -DBrowser=Chrome