version: 2
jobs:
  build:
    docker:
      - image: jamesdbloom/docker-java8-maven
      - image: selenium/standalone-chrome

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn test -Ddocker=true

      - run: mvn coveralls:report