version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: selenium/standalone-chrome
        environment:
          port: 4444:4444

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m
      CC_TEST_REPORTER_ID:

    dependencies:
      post:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn clean test jacoco:report coveralls:report -Dremote=true
      - store_test_results:
          path: target/surefire-reports
